import DatasetResults from './DatasetResults';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity,ArrowDownToLine,Clock,Database,Pause,Play,RefreshCw,Radio,ChevronLeft,ChevronRight} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {api,colors,labels,variables,variableNames,units,num,date,type Station,downloadData} from './api';

type Props={stations:Station[];notify:(s:string)=>void;refresh:()=>void;onOpen:(id:string)=>void};
const utcDay=(t:number)=>new Date(t).toISOString().slice(0,10);
function dates(from:string,to:string){const q=new URLSearchParams();if(from)q.set('start',from+'T00:00:00Z');if(to)q.set('end',new Date(Date.parse(to+'T00:00:00Z')+86400000).toISOString());return q;}
function Chart({data,variable,compare=false}:{data:any[];variable:number;compare?:boolean}){return <ResponsiveContainer width="100%" height={300}><LineChart data={data}><CartesianGrid stroke="#dce9f7" strokeDasharray="3 3"/><XAxis dataKey="timestamp" tickFormatter={v=>new Date(v).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',timeZone:'UTC'})} minTickGap={60} tick={{fontSize:11}}/><YAxis domain={['auto','auto']} tick={{fontSize:11}} width={55}/><Tooltip labelFormatter={v=>`${new Date(v).toLocaleString('en-GB',{timeZone:'UTC'})} UTC`} formatter={(v:any)=>num(v,2)}/><Legend/><Line type="monotone" dataKey={variables[variable]} name={`${variableNames[variable]} (${units[variable]})`} stroke={['#ff6479','#238eff','#00b997'][variable]} dot={false} strokeWidth={2} isAnimationActive={false} connectNulls={false}/>{compare&&<Line dataKey="comparison" name="Comparison station" stroke="#9866df" strokeDasharray="5 3" dot={false} isAnimationActive={false} connectNulls={false}/>}</LineChart></ResponsiveContainer>}
export default function DataWorkspace({stations,notify,refresh,onOpen}:Props){
 const [mode,setMode]=useState<'history'|'monitor'|'evaluation'>('history');
 return <><div className="page-heading"><div><h1>Observation explorer</h1><p>Understand the past. Follow the network as new readings arrive.</p></div><div className="data-mode" role="group" aria-label="Observation mode"><button className={mode==='history'?'active':''} onClick={()=>setMode('history')}><Clock size={16}/>Historical analysis</button><button className={mode==='monitor'?'active':''} onClick={()=>setMode('monitor')}><Radio size={16}/>Live monitoring</button><button className={mode==='evaluation'?'active':''} onClick={()=>setMode('evaluation')}><Database size={16}/>Dataset & ML results</button></div></div>{mode==='evaluation'?<DatasetResults stations={stations}/>:mode==='history'?<History stations={stations} notify={notify} onOpen={onOpen}/>:<Monitor stations={stations} notify={notify} refresh={refresh} onOpen={onOpen}/>}</>
}
function History({stations,notify,onOpen}:Omit<Props,'refresh'>){
 const [station,setStation]=useState(stations[0]?.id||''),[compare,setCompare]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[bucket,setBucket]=useState('hour'),[source,setSource]=useState('all'),[page,setPage]=useState(1),[variable,setVariable]=useState(0),[data,setData]=useState<any>(null),[comparison,setComparison]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef(0);
 useEffect(()=>{const n=++request.current;setBusy(true);setError('');const q=dates(from,to);q.set('bucket',bucket);q.set('page',String(page));q.set('source',source);Promise.all([api(`/history/${station}?${q}`),compare?api(`/history/${compare}?${q}`):Promise.resolve(null)]).then(([a,b])=>{if(n===request.current){setData(a);setComparison(b)}}).catch(e=>{if(n===request.current)setError(e.message)}).finally(()=>{if(n===request.current)setBusy(false)});return()=>{request.current++}},[station,compare,from,to,bucket,source,page]);
 function range(days:number){const end=data?.available_end?Date.parse(data.available_end):Date.now();setTo(utcDay(end));setFrom(utcDay(end-(days-1)*86400000));setPage(1)}
 const peers=new Map(comparison?.series.map((r:any)=>[r.timestamp,r[variables[variable]]])||[]);
 const series=(data?.series||[]).map((r:any)=>({...r,comparison:peers.get(r.timestamp)??null}));
 async function download(){try{await downloadData(`/history/${station}/export?${dates(from,to)}&source=${source}`,`skyguard-${station}-history.csv`);notify('Selected history exported with source and scoring status')}catch(e:any){notify(e.message)}}
 return <div className="data-workspace"><section className="panel data-toolbar"><label>Station<select aria-label="History station" value={station} onChange={e=>{setStation(e.target.value);setPage(1)}}>{stations.map(s=><option key={s.id} value={s.id}>{s.city} · {s.state} · {s.id}</option>)}</select></label><label>Compare station<select aria-label="Compare station" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{stations.filter(s=>s.id!==station).map(s=><option key={s.id} value={s.id}>{s.city} · {s.id}</option>)}</select></label><label>From (UTC)<input aria-label="History start date" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>Through (UTC)<input aria-label="History end date" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label><label>Resolution<select value={bucket} onChange={e=>setBucket(e.target.value)}><option value="hour">Hourly mean</option><option value="day">Daily mean</option></select></label><label>Records<select value={source} onChange={e=>{setSource(e.target.value);setPage(1)}}><option value="all">Current history edition</option><option value="original">Original records (preserved)</option><option value="processed">Online processed</option><option value="archive">Synthetic archive</option></select></label><div className="data-presets">{[1,7,30,90].map(d=><button key={d} className="button outline" onClick={()=>range(d)}>{d===1?'Latest day':`${d} days`}</button>)}<button className="text-button" onClick={()=>{setFrom('');setTo('');setPage(1)}}>All available</button><button className="button outline" disabled={busy||!!error||!data?.total} onClick={download}><ArrowDownToLine size={15}/>Export range</button></div></section>
 <div className="notice"><Database size={18}/><span>{stations.find(s=>s.id===station)?.network==='SkyGuard simulation'?'Demo archive: hourly synthetic T/P/RH. See Dataset & ML results for current coverage. Archive samples are unscored and excluded from online model history.':'Historical records from registered station ingestion.'} Varied historical demo samples are unscored. Choose Original records to inspect preserved earlier editions and decisions.</span></div>
 {error?<div className="error-banner" role="alert">{error}</div>:data&&<><div className="history-kpis">{variables.map((v,i)=><section className="panel" key={v}><span className="muted">{variableNames[i]} · selected range</span><strong>{num(data.statistics[v].mean)} <small>{units[i]}</small></strong><span>Min {num(data.statistics[v].min)} · Max {num(data.statistics[v].max)}</span></section>)}<section className="panel"><span className="muted">Stored observations</span><strong>{data.total.toLocaleString()}</strong><span>{data.scored.toLocaleString()} scored · {data.unscored.toLocaleString()} unscored</span></section></div><section className="panel"><div className="panel-heading"><h2><Activity size={19}/>Historical measurements</h2><select aria-label="History measurement" value={variable} onChange={e=>setVariable(Number(e.target.value))}>{variableNames.map((v,i)=><option key={v} value={i}>{v}</option>)}</select></div><p className="muted">{bucket==='hour'?'Hourly':'Daily'} means · UTC buckets · {data.flagged} scored observations require review{busy?' · Updating…':''}</p>{data.total?<Chart data={series} variable={variable} compare={!!compare}/>:<div className="empty">No observations in this range. Try All available.</div>}<p className="micro">Available: {data.available_start?.slice(0,10)||'—'} to {data.available_end?.slice(0,10)||'—'} · Historical graphs describe stored measurements, not forecast accuracy.</p></section>
 <section className="panel"><div className="panel-heading"><h2><Database size={18}/>Observation ledger</h2><button className="text-button" onClick={()=>onOpen(station)}>Open station evidence →</button></div><div className="table-wrap"><table><thead><tr><th>Observed (local time)</th><th>T °C</th><th>P hPa</th><th>RH %</th><th>Source</th><th>Decision</th></tr></thead><tbody>{data.rows.map((r:any)=><tr key={r.observation_id}><td>{date(r.timestamp)}</td>{variables.map(v=><td key={v}>{num(r[v],2)}</td>)}<td>{r.source==='synthetic_archive'?'Synthetic archive':r.source}</td><td><span className="badge" style={{color:colors[r.classification]||'#6e81a4'}}>{labels[r.classification]||'Unscored archive'}</span></td></tr>)}</tbody></table></div><div className="data-pagination"><span>{data.total?`${(page-1)*50+1}–${Math.min(page*50,data.total)} of ${data.total.toLocaleString()}`:'No records'}</span><button aria-label="Previous history page" disabled={page<=1||busy} onClick={()=>setPage(page-1)}><ChevronLeft size={18}/></button><span>Page {page} / {Math.max(1,data.pages)}</span><button aria-label="Next history page" disabled={page>=data.pages||busy} onClick={()=>setPage(page+1)}><ChevronRight size={18}/></button></div></section></>}
 {!data&&busy&&<div className="loading">Loading immutable history…</div>}</div>
}
function Monitor({stations,notify,refresh,onOpen}:Props){
 const [data,setData]=useState<any>(null),[automatic,setAutomatic]=useState(true),[interval,setIntervalValue]=useState(30),[feedStation,setFeedStation]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const d=await api(`/monitor${feedStation?'?station_id='+encodeURIComponent(feedStation):''}`);setData(d);setChecked(new Date().toISOString());setError('')}catch(e:any){setError(e.message)}},[feedStation]);
 useEffect(()=>{load();if(!automatic)return;const timer=setInterval(load,10000);return()=>clearInterval(timer)},[load,automatic]);
 async function act(sample=false){setBusy(true);try{const d=await api(sample?'/monitor/sample':'/monitor',{method:'POST',...(sample?{}:{body:JSON.stringify({enabled:!data.enabled,interval_seconds:interval})})});setData(d);await load();refresh();notify(sample?'A new network sample was processed':d.enabled?'Continuous simulation started':'Continuous simulation paused')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
 const stationName=(id:string)=>stations.find(s=>s.id===id)?.city||id;
 return <div className="data-workspace">{error&&<div className="error-banner">{error}</div>}{data&&<><section className="panel monitor-control"><div><span className="eyebrow">{data.mode==='simulation'?'SIMULATED STREAM':'INCOMING TELEMETRY'}</span><h2><span className={`status-dot ${data.enabled?'':'paused'}`}/>{data.mode==='simulation'?(data.enabled?'Monitoring simulation is running':'Monitoring simulation is paused'):'Listening for station observations'}</h2><p>{data.mode==='simulation'?'Each cycle advances the network by 10 simulated minutes and runs the existing detection pipeline.':'New HTTP / MQTT bridge observations appear after ingestion. No external weather provider is configured here.'}</p></div><div className="monitor-actions">{data.mode==='simulation'&&<><label>Cycle interval<select aria-label="Monitoring interval" disabled={data.enabled||busy} value={interval} onChange={e=>setIntervalValue(Number(e.target.value))}>{[10,30,60,300].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label><button className="button primary" disabled={busy} onClick={()=>act()}>{data.enabled?<Pause size={16}/>:<Play size={16}/>} {data.enabled?'Pause stream':'Start stream'}</button><button className="button outline" disabled={busy||data.enabled} onClick={()=>act(true)}><Activity size={16}/>{busy?'Processing…':'Sample once'}</button></>}<button className="button outline" onClick={load}><RefreshCw size={16}/>Check for updates</button></div></section>{data.error&&<div className="error-banner">Stream stopped: {data.error}</div>}
 <div className="history-kpis"><section className="panel"><span className="muted">Network stations</span><strong>{stations.length}</strong><span>{stations.filter(s=>s.online).length} currently online</span></section><section className="panel"><span className="muted">Packets received / last minute</span><strong>{data.received_last_minute}</strong><span>Excludes archive import</span></section><section className="panel"><span className="muted">Latest receipt</span><strong className="date-value">{date(data.last_received_at)}</strong><span>Server receipt time</span></section><section className="panel"><span className="muted">{data.mode==='simulation'?'Simulation clock':'Server time'}</span><strong className="date-value">{date(data.mode==='simulation'?data.clock:data.server_time)}</strong><span>{data.cycles||0} simulation cycles completed</span></section></div>
 <section className="panel"><div className="panel-heading"><h2><Radio size={19}/>Rolling observation feed</h2><select aria-label="Feed station" value={feedStation} onChange={e=>setFeedStation(e.target.value)}><option value="">All stations</option>{stations.map(s=><option key={s.id} value={s.id}>{s.city} · {s.state} · {s.id}</option>)}</select><label className="checkbox-option"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/>Auto-refresh · 10s</label></div><p className="muted">30 latest processed observations · last checked {date(checked)} · {data.mode==='simulation'?'synthetic measurements':'received station measurements'}</p><div className="table-wrap"><table><thead><tr><th>Event time</th><th>Station</th><th>T °C</th><th>P hPa</th><th>RH %</th><th>Classification</th><th>Evidence</th></tr></thead><tbody>{data.feed.map((r:any)=><tr key={r.id}><td>{date(r.timestamp)}</td><td><button className="text-button" onClick={()=>onOpen(r.station_id)}>{stationName(r.station_id)}<small>{r.station_id}</small></button></td>{variables.map(v=><td key={v}>{num(r[v])}</td>)}<td style={{color:colors[r.classification]}}>{labels[r.classification]}</td><td>{num((r.evidence_strength||0)*100,0)}/100</td></tr>)}</tbody></table></div>{!data.feed.length&&<div className="empty">Waiting for observations. Register a station and send T/P/RH through the ingestion API.</div>}</section></>}{!data&&!error&&<div className="loading">Connecting to monitoring…</div>}</div>
}
