import {useEffect,useState} from 'react';
import {Database,FlaskConical,ChevronLeft,ChevronRight} from 'lucide-react';
import {api,num,date,labels,colors,variables,type Station} from './api';
export default function DatasetResults({stations}:{stations:Station[]}){
 const [data,setData]=useState<any>(null),[rows,setRows]=useState<any>(null),[station,setStation]=useState(''),[scenario,setScenario]=useState(''),[errors,setErrors]=useState(false),[page,setPage]=useState(1),[error,setError]=useState('');
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;async function load(){try{const d=await api('/dataset');if(active){setData(d);if(d.evaluation.status==='running')timer=setTimeout(load,10000)}}catch(e:any){if(active)setError(e.message)}}load();return()=>{active=false;clearTimeout(timer)}},[]);
 useEffect(()=>{let active=true;api(`/dataset/predictions?station_id=${station}&scenario=${scenario}&errors_only=${errors}&page=${page}`).then(r=>{if(active)setRows(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[station,scenario,errors,page,data?.evaluation?.completed_stations]);
 if(error)return <div className="error-banner">{error}</div>;if(!data)return <div className="loading">Loading dataset and measured evaluation…</div>;
 const m=data.metrics,pct=(n:number)=>n==null?'—':num(n*100)+'%';
 return <div className="data-workspace"><div className="history-kpis"><section className="panel"><span className="muted">Synthetic station network</span><strong>{data.stations.toLocaleString()}</strong><span>Generated demonstration sites</span></section><section className="panel"><span className="muted">Stored observations</span><strong>{data.observations.toLocaleString()}</strong><span>{data.archive.days||30} days of hourly archive</span></section><section className="panel"><span className="muted">Labeled evaluation samples</span><strong>{m.run_id?m.observations.toLocaleString():'Pending'}</strong><span>{m.station_count||data.evaluation.completed_stations||0} stations evaluated</span></section><section className="panel"><span className="muted">Fault detection F1</span><strong>{m.run_id?pct(m.fault_f1):'—'}</strong><span>Measured hybrid pipeline · synthetic test</span></section></div>
 <section className="panel"><div className="panel-heading"><h2><FlaskConical size={18}/>ML evaluation on stored history</h2><span className="tag">{data.evaluation.status||'Not run'}</span></div><p className="muted">Fixed Isolation Forest + temporal, physics and spatial evidence. Each station contributes 48 hours of causal warm-up and 24 labeled test copies. Raw archive values are preserved.</p>{m.run_id?<><div className="inline-stats"><div><span>Fault precision</span><strong>{pct(m.fault_precision)}</strong></div><div><span>Fault recall</span><strong>{pct(m.fault_recall)}</strong></div><div><span>False alerts on normal</span><strong>{pct(m.false_alert_rate)}</strong></div><div><span>Abstention</span><strong>{pct(m.abstention_rate)}</strong></div></div><p className="micro">Test period: {m.test_start?.slice(0,10)} to {m.test_end?.slice(0,10)} · hourly observations · 48 prior hours per site.</p>{m.isolation_forest&&<div className="notice"><FlaskConical size={18}/><span>Isolation Forest alone: novelty precision {pct(m.isolation_forest.novelty_precision)}, recall {pct(m.isolation_forest.novelty_recall)} on {m.isolation_forest.scored.toLocaleString()} samples at the unchanged validation threshold. Novelty includes weather and ambiguous changes; it is not a fault classification.</span></div>}<div className="table-wrap"><table><thead><tr><th>Scenario</th><th>Test samples</th><th>Exact class accuracy</th></tr></thead><tbody>{m.scenarios.map((s:any)=><tr key={s.scenario}><td>{s.scenario}</td><td>{s.samples.toLocaleString()}</td><td>{pct(s.accuracy)}</td></tr>)}</tbody></table></div><p className="micro">Run {m.run_id} · completed {date(m.completed_at)} · {num(m.duration_seconds/60)} minutes · model unchanged.</p><div className="notice"><FlaskConical size={18}/><span>Synthetic development results, not field accuracy. These metrics use the original archive generator; the new regional simulation has not been benchmarked. Only the labeled test copies were evaluated—not the entire archive. Hourly sampling differs from training cadence; frozen-sensor performance may be weak.</span></div></>:<p>Evaluation {data.evaluation.status||'not available'}: {data.evaluation.completed_stations||0} / {data.evaluation.total_stations||data.stations} stations. Results update automatically.</p>}</section>
 {m.run_id&&<section className="panel"><div className="panel-heading"><h2>Classification confusion matrix</h2><span className="micro">Rows: ground truth · columns: predicted</span></div><div className="table-wrap"><table className="confusion-table"><thead><tr><th>Actual / predicted</th>{m.class_order.map((c:string)=><th key={c}>{labels[c]}</th>)}</tr></thead><tbody>{m.confusion_matrix.map((row:number[],i:number)=><tr key={i}><th>{labels[m.class_order[i]]}</th>{row.map((n,j)=><td key={j} style={{background:n?(i===j?'#d6f5e9':'#ffe6eb'):undefined,fontWeight:n?700:400}}>{n.toLocaleString()}</td>)}</tr>)}</tbody></table></div></section>}
 <section className="panel"><div className="panel-heading"><h2><Database size={18}/>Prediction audit</h2><span className="micro">IF score is novelty evidence, not probability</span></div><div className="evaluation-filters"><label>Station<select aria-label="Evaluation station" value={station} onChange={e=>{setStation(e.target.value);setPage(1)}}><option value="">All stations</option>{stations.map(s=><option key={s.id} value={s.id}>{s.city} · {s.id}</option>)}</select></label><label>Scenario<select aria-label="Evaluation scenario" value={scenario} onChange={e=>{setScenario(e.target.value);setPage(1)}}><option value="">All scenarios</option>{['normal','spike','drift','freeze','weather','ambiguous','invalid'].map(s=><option key={s}>{s}</option>)}</select></label><label className="checkbox-option"><input type="checkbox" checked={errors} onChange={e=>{setErrors(e.target.checked);setPage(1)}}/>Misclassified only</label></div><div className="table-wrap"><table><thead><tr><th>Station / event time</th><th>Scenario</th><th>Original T/P/RH</th><th>Test T/P/RH</th><th>Ground truth</th><th>Prediction</th><th>IF score</th></tr></thead><tbody>{rows?.rows.map((r:any)=><tr key={r.source_observation_id}><td>{r.station_id}<small className="audit-time">{date(r.timestamp)}</small></td><td>{r.scenario}</td><td>{variables.map(v=>num(r.original[v])).join(' / ')}</td><td>{variables.map(v=>num(r.test_observation[v])).join(' / ')}</td><td>{labels[r.truth]}</td><td style={{color:r.correct?'#009875':'#ef526b'}}>{labels[r.prediction]}</td><td>{num(r.ml_score,3)}</td></tr>)}</tbody></table></div>{!rows?.total&&<div className="empty">No matching predictions.</div>}<div className="data-pagination"><span>{rows?.total.toLocaleString()||0} matching predictions</span><button aria-label="Previous evaluation page" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={18}/></button><span>Page {page}</span><button aria-label="Next evaluation page" disabled={!rows||page*50>=rows.total} onClick={()=>setPage(page+1)}><ChevronRight size={18}/></button></div></section>
 <section className="panel"><div className="panel-heading"><h2>Archive coverage by station</h2><span>{data.coverage.length} stations</span></div><div className="table-wrap coverage-table"><table><thead><tr><th>Station</th><th>Location</th><th>Observations</th><th>First stored</th><th>Latest stored</th></tr></thead><tbody>{data.coverage.map((r:any)=><tr key={r.station_id}><td>{r.station_id}</td><td>{r.city}, {r.state}</td><td>{r.observations.toLocaleString()}</td><td>{date(r.first)}</td><td>{date(r.last)}</td></tr>)}</tbody></table></div></section></div>
}
