import {useEffect,useState,useMemo} from 'react';
import {api,colors,date,labels,num,units,variables,variableNames,type Station} from './api';

export function healthTier(s:Station){return !s.online||s.health<70?'DEGRADED':s.health<90||!['NORMAL','GENUINE_WEATHER'].includes(s.classification)?'WATCH':'HEALTHY'}
export function StationDirectory({stations,onOpen}:{stations:Station[];onOpen:(id:string)=>void}){
 const [filter,setFilter]=useState('ALL'),[page,setPage]=useState(0);
 const stationIds=stations.map(s=>s.id).join('|');
 useEffect(()=>setPage(0),[stationIds,filter]);
 const shown=stations.filter(s=>filter==='ALL'||healthTier(s)===filter);
 useEffect(()=>setPage(p=>Math.min(p,Math.max(0,Math.ceil(shown.length/12)-1))),[shown.length]);
 return <section className="panel station-directory"><div className="directory-filters"><strong>Station intelligence</strong>{['ALL','HEALTHY','WATCH','DEGRADED'].map(t=><button key={t} className={`button ${filter===t?'primary':'outline'}`} onClick={()=>setFilter(t)}>{t} · {stations.filter(s=>t==='ALL'||healthTier(s)===t).length}</button>)}</div><p className="micro">Health tiers: healthy ≥90 with normal/weather status; watch needs attention; degraded &lt;70 or offline. Operational index, not failure probability.</p><div className="station-card-grid">{shown.slice(page*12,page*12+12).map(s=><button className="station-directory-card" onClick={()=>onOpen(s.id)} key={s.id}><div><span>{s.id}</span><span className={`tier ${healthTier(s).toLowerCase()}`}>{healthTier(s)}</span></div><h3>{s.city}</h3><p>{s.state}</p><div className="directory-values">{variables.map((v,i)=><span key={v}><small>{variableNames[i]}</small><b>{num(s.latest?.[v])} {units[i]}</b></span>)}</div><div><span><i className="status-dot" style={{background:colors[s.classification]}}/> {labels[s.classification]}</span><strong>{num(s.health,0)}/100</strong></div><footer>Open station intelligence →</footer></button>)}</div>{!shown.length&&<p>No stations match this health tier.</p>}<div className="data-pagination"><span>{shown.length} matching stations</span><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>{page+1} / {Math.max(1,Math.ceil(shown.length/12))}</span><button disabled={(page+1)*12>=shown.length} onClick={()=>setPage(page+1)}>Next</button></div></section>
}
export function LocalStationMap({station,stations,onOpen}:{station:Station;stations:Station[];onOpen:(id:string)=>void}){
 const [geo,setGeo]=useState<any>(null),[failed,setFailed]=useState(false),[extent,setExtent]=useState(220),[selected,setSelected]=useState(station.id);
 useEffect(()=>{let active=true;fetch('/india-states.geojson').then(r=>{if(!r.ok)throw Error('Map unavailable');return r.json()}).then(g=>{if(active)setGeo(g)}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[]);
 useEffect(()=>{setSelected(station.id);setExtent(220)},[station.id]);
 const lat=station.latitude,lon=station.longitude,cos=Math.cos(lat*Math.PI/180);
 const xy=(longitude:number,latitude:number)=>[(longitude-lon)*111.32*cos,-(latitude-lat)*111.32];
 const nearby=useMemo(()=>stations.map(s=>({station:s,distance:Math.hypot((s.longitude-lon)*111.32*cos,(s.latitude-lat)*111.32)})).filter(s=>s.distance<=extent*1.3).sort((a,b)=>a.distance-b.distance),[stations,lat,lon,cos,extent]);
 const focused=stations.find(s=>s.id===selected)||station;
 const pixels=extent/110;
 return <div className="local-station-map"><div className="local-map-heading"><strong>{station.city}</strong><span>{station.state}</span></div>
 <div className="local-map-canvas">{geo?<svg viewBox={`${-extent} ${-extent*.8} ${extent*2} ${extent*1.6}`} role="group" aria-label={`Regional map around ${station.city}, with nearby stations`}>
 <defs><pattern id={`grid-${station.id}`} width={extent/4} height={extent/4} patternUnits="userSpaceOnUse"><path d={`M ${extent/4} 0 L 0 0 0 ${extent/4}`} fill="none" stroke="#c1dae9" strokeWidth={pixels*.5}/></pattern></defs>
 <rect x={-extent} y={-extent*.8} width={extent*2} height={extent*1.6} fill="#e1f0fa"/>
 {geo.features.map((f:any)=><path key={f.properties.NAME_1} d={f.geometry.coordinates.map((poly:number[][][])=>poly.map(r=>r.map((p,i)=>`${i?'L':'M'}${xy(p[0],p[1]).join(' ')}`).join(' ')+'Z').join(' ')).join(' ')} fill={f.properties.NAME_1===station.state?'#c9e3d7':'#e2ede5'} fillRule="evenodd" stroke="#8fb3a7" strokeWidth={pixels*.7}><title>{f.properties.NAME_1}</title></path>)}
 <rect x={-extent} y={-extent*.8} width={extent*2} height={extent*1.6} fill={`url(#grid-${station.id})`} pointerEvents="none"/>
 {nearby.filter(n=>Math.abs(xy(n.station.longitude,n.station.latitude)[0])<extent-8*pixels&&Math.abs(xy(n.station.longitude,n.station.latitude)[1])<extent*.8-8*pixels).reverse().map(({station:s})=>{const [x,y]=xy(s.longitude,s.latitude);return <g key={s.id} role="button" tabIndex={0} aria-label={`Select ${s.city} ${s.id}`} onClick={()=>setSelected(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(s.id)}}} style={{cursor:'pointer'}}><title>{s.city} · {labels[s.classification]}</title>{s.id===selected&&<circle cx={x} cy={y} r={9*pixels} fill="none" stroke="#168aff" strokeWidth={2*pixels}/>}<circle cx={x} cy={y} r={(s.id===station.id?5:3.5)*pixels} fill={colors[s.classification]||'#819bb5'} stroke="white" strokeWidth={pixels}/>{s.id===station.id&&<text x={x} y={y-13*pixels} textAnchor="middle" fontSize={10*pixels} fill="#193f64" paintOrder="stroke" stroke="#f3faff" strokeWidth={3*pixels}>{s.city}</text>}</g>})}
 <text x={extent-35*pixels} y={-extent*.8+20*pixels} fontSize={12*pixels} fill="#28567d">N ↑</text>
 <path d={`M ${-extent+15*pixels} ${extent*.8-20*pixels} h ${extent/2}`} stroke="#426e91" strokeWidth={2*pixels}/><text x={-extent+15*pixels} y={extent*.8-25*pixels} fontSize={10*pixels} fill="#426e91">{Math.round(extent/2)} km</text>
 </svg>:<div className="local-map-placeholder">{failed?'Regional map unavailable. Coordinates and station details remain below.':'Loading regional map…'}</div>}
 <div className="local-map-controls"><button aria-label="Zoom into station location" disabled={extent<=27.5} onClick={()=>setExtent(e=>e/2)}>+</button><button aria-label="Zoom out of station location" disabled={extent>=880} onClick={()=>setExtent(e=>e*2)}>−</button><button aria-label="Reset station location" onClick={()=>{setExtent(220);setSelected(station.id)}}>↺</button></div></div>
 <div className="local-map-details"><strong><i className="status-dot" style={{background:colors[focused.classification]}}/>{focused.city} · {labels[focused.classification]}</strong><small>{focused.id} · {num(focused.latitude,4)}° N, {num(focused.longitude,4)}° E</small><small>{num(focused.latest?.temperature_c)} °C · {num(focused.latest?.pressure_hpa)} hPa · {num(focused.latest?.relative_humidity_pct)}% RH</small><small>{focused.last_update?date(focused.last_update):'No observation'} · {focused.online?'Online':'Offline'}</small>{focused.id!==station.id&&<button className="text-button" onClick={()=>onOpen(focused.id)}>Open this station report →</button>}</div>
 <p className="micro">Regional boundaries and station locations · {nearby.length} stations within approximately {Math.round(extent*1.3)} km. Street detail opens externally.</p>
 <a href={`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=10/${lat}/${lon}`} target="_blank" rel="noreferrer">View streets on OpenStreetMap ↗</a></div>
}
export default function StationIntelligence({station,clock,onOpen}:{station:Station;clock:number;onOpen:(id:string)=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');api(`/stations/${station.id}/intelligence`,{signal:c.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[station.id,station.last_update,clock]);
 if(error)return <div className="error-banner">{error}</div>;
 if(!data)return <div className="loading">Loading station intelligence…</div>;
 if(!data.available)return <div className="panel">{data.reason}</div>;
 return <div className="intelligence-workspace"><section className="panel"><div className="panel-heading"><h2>Current snapshot & telemetry</h2><span className={`tier ${healthTier(station).toLowerCase()}`}>{healthTier(station)}</span></div><div className="snapshot-grid">{variables.map((v,i)=><div key={v}><small>{variableNames[i]}</small><strong style={{color:['#ff566c','#168aff','#08b88b'][i]}}>{num(station.latest?.[v])} {units[i]}</strong></div>)}</div><p>Last telemetry: {date(data.as_of)} · {data.source}{data.source_version?` / ${data.source_version}`:''}</p><p className="micro">{data.scope}</p><div className="inline-stats"><div><span>24-hour completeness</span><strong>{num(data.coverage.percent)}%</strong><small>{data.coverage.observed} / {data.coverage.expected} expected readings</small></div><div><span>Packet age at network clock</span><strong>{num(data.coverage.last_packet_age_seconds/60)} min</strong></div><div><span>Decision stage</span><strong>{data.decision_stage||'Unavailable'}</strong></div></div></section>
 <section className="panel"><div className="panel-heading"><h2>Temporal statistics & sensor patterns</h2><span className="tag">Past-only</span></div><p className="micro">Up to 36 prior trusted samples from the same source version. Classical z is unavailable with insufficient/constant history. Robust z uses median/MAD with a sensor-scale floor; neither is a probability.</p><div className="table-wrap"><table><thead><tr><th>Parameter</th><th>Prior n</th><th>Mean</th><th>Median</th><th>Std dev</th><th>Z-score</th><th>Robust z</th><th>Change/min</th><th>Frozen</th></tr></thead><tbody>{data.statistics.map((r:any,i:number)=><tr key={r.variable}><td>{variableNames[i]}</td><td>{r.samples}</td>{['mean','median','std','z_score','robust_z','rate_per_minute'].map(k=><td key={k}>{num(r[k],2)}</td>)}<td>{r.frozen?'Detected':'No'}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panel-heading"><h2>Virtual Buddy · nearby station context</h2><span className="tag">{data.buddy.available?'Available':'Insufficient evidence'}</span></div><p>{data.buddy.method}</p><p className="micro">Reconstructed context at {date(data.as_of)}; supports investigation and does not change the stored decision. Requires ≥3 fresh trusted neighbors. NWP is excluded by this project’s T/P/RH contract.</p>{data.buddy.reason&&<div className="notice">{data.buddy.reason}</div>}<div className="snapshot-grid">{variables.map((v,i)=><div key={v}><small>{variableNames[i]} · buddy estimate</small><strong>{num(data.buddy.estimates[v])} {units[i]}</strong></div>)}</div><div className="table-wrap"><table><thead><tr><th>Trusted neighbor</th><th>Distance</th><th>Age</th><th>Δ T</th><th>Δ P</th><th>Δ RH</th></tr></thead><tbody>{data.buddy.neighbors.map((n:any)=><tr key={n.station_id}><td><button className="text-button" onClick={()=>onOpen(n.station_id)}>{n.city} · {n.station_id}</button></td><td>{num(n.distance_km)} km</td><td>{num(n.age_seconds/60)} min</td>{variables.map(v=><td key={v}>{num(n.deltas[v],2)}</td>)}</tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panel-heading"><h2>Detection layers & decision reasoning</h2><span style={{color:colors[data.classification]}}>{labels[data.classification]}</span></div><div className="pipeline-grid">{data.layers.map((layer:any)=><article key={layer.detector_name}><div><strong>{layer.detector_name}</strong><span>{layer.available?`${num(layer.score*100,0)}/100 evidence`:'Unavailable'}</span></div><p>{layer.human_explanation}</p></article>)}</div><p><strong>Recommended action:</strong> {data.recommendation}</p><p className="muted">{data.counterfactual}</p><p className="micro">These are the recorded inputs to the existing hybrid decision logic. Evidence scores are uncalibrated and correlated; they are not added into a confidence probability.</p></section></div>
}
